server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/skeleton?useSSL=false&allowPublicKeyRetrieval=true
    username: amjad
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
security:
  checkAuthentication:
    -
        path: "/authentication/logout"
        method: "POST"
    -
        path: "/user/"
        method: "POST"
    -
        path: "/user/"
        method: "DELETE"
    -
        path: "/user/change_password"
        method: "PUT"
feign-client:
  order:
    baseUrl: http://localhost:8084